# docker-compose.yml
# Optional: For local development and testing of Ansible playbooks

version: '3.8'

services:
  ansible-controller:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh:ro
      - ~/.aws:/root/.aws:ro
    working_dir: /workspace
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
    command: tail -f /dev/null  # Keep container running

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws:ro
    working_dir: /workspace
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
    command: tail -f /dev/null  # Keep container running